### ISSUE TITLE
ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by railsfactory-vishnuroshan** [elastic/elasticsearch-js-mock#23]
I am using next.js project with typescript.

I am facing this issue when jest tries to run the mock file

```
ReferenceError: setImmediate is not defined

      12 | }
      13 |
    > 14 | import { Client } from '@elastic/elasticsearch';
         | ^
      15 | import Mock from '@elastic/elasticsearch-mock';
      16 |
      17 | const mock = new Mock();

      at Object.<anonymous> (node_modules/@elastic/elasticsearch/lib/Helpers.js:27:30)
      at Object.<anonymous> (node_modules/@elastic/elasticsearch/index.js:29:17)
      at Object.<anonymous> (__mocks__/elasticsearch.ts:14:1)
```

in the file `__mocks__/elasticsearch.ts`
```
import { Client } from '@elastic/elasticsearch';
import Mock from '@elastic/elasticsearch-mock';

const mock = new Mock();
const client = new Client({
  node: 'http://localhost:9200',
  Connection: mock.getConnection(),
});

mock.add(
  {
    method: 'GET',
    path: '/',
  },
  () => {
    return { status: 'ok' };
  }
);

client.info(console.log);

```

**Comment by yidah** [comment]
Hi,

I am having the same problem as @railsfactory-vishnuroshan in a node JS project, same configuration, same error. Has somebody solved this error?

Thanks for your help.

**Comment by delvedor** [comment]
Hello! Very likely Jest is doing something weird behind the scenes and breaks the client code.
See https://github.com/facebook/jest/issues/2549.

**Comment by railsfactory-sivamanikandan** [comment]
Hi All,
This issue is due to test environment, if you are using --env=jsdom  you will get this issue.
Please try to remove this --env=jsdom  or use --env=node

**Comment by railsfactory-vishnuroshan** [comment]
The solution given by @railsfactory-sivamanikandan worked. I am closing this issue
